apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  selector:
    app: heart-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
